db.trabajaodor.drop()
db.trabajador.insertMany([
    {
        _id_empleado: 1,
        Nombre: "Jairo",
        Apellidos: "Rastrojo Rodríguez",
        Puesto: "Gerente",
        Sueldo: 1200,
        Fecha_Contrato: new Date("2015-07-04"),
        Horario: ["Lunes", "Miercoles", "Jueves", "Sabado"],
    },
    {
        _id_empleado: 2,
        Nombre: "Silvia",
        Apellidos: "Espínola",
        Puesto: "Cuidado animales",
        Sueldo: 1100,
        Fecha_Contrato: new Date("2015-08-01"),
        Horario: ["Lunes", "Martes", "Jueves", "Viernes"],
    },
    {
        _id_empleado: 3,
        Nombre: "José",
        Apellidos: "Palacios Montes",
        Puesto: "Limpiador",
        Sueldo: 900,
        Fecha_Contrato: new Date("2016-07-04"),
        Horario: ["Lunes", "Miercoles", "Viernes"],
    },
    {
        _id_empleado: 4,
        Nombre: "Francisco",
        Apellidos: "Laguna Benitez",
        Puesto: "Cajero",
        Sueldo: 900,
        Fecha_Contrato: new Date("2015-02-14"),
        Horario: ["Lunes", "Miercoles", "Viernes"],
    },
    {
        _id_empleado: 5,
        Nombre: "Mariangeles",
        Apellidos: "Laguna Benitez",
        Puesto: "Cuidado animales",
        Sueldo: 800,
        Fecha_Contrato: new Date("2018-04-30"),
        Horario: ["Miercoles", "Sabado", "Domingo"],
    },
    {
        _id_empleado: 6,
        Nombre: "Salvador",
        Apellidos: "Oliva",
        Puesto: "Cajero",
        Sueldo: 400,
        Fecha_Contrato: new Date("2019-09-12"),
        Horario: ["Martes", "Jueves"],
    },
    {
        _id_empleado: 7,
        Nombre: "Ana Belén",
        Apellidos: "Rastrojo Rodríguez",
        Puesto: "Limpiadora",
        Sueldo: 800,
        Fecha_Contrato: new Date("2020-01-2"),
        Horario: ["Martes", "Jueves", "Sabado", "Domingo"],
    },
])